/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    'IconMaterialSymbolsLight:darkModeOutline': typeof import('~icons/material-symbols-light/dark-mode-outline')['default']
    'IconMaterialSymbolsLight:lightModeOutline': typeof import('~icons/material-symbols-light/light-mode-outline')['default']
    'IconMaterialSymbolsLight:wifi': typeof import('~icons/material-symbols-light/wifi')['default']
    PhotoThumbnail: typeof import('./src/components/PhotoThumbnail.vue')['default']
  }
}
