// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {types} from '../models';

export function DownloadFile(arg1:string,arg2:string):Promise<main.DownloadFileResponse>;

export function GetDcimFolder():Promise<string>;

export function GetImageThumbnail(arg1:string):Promise<types.ImageResponse>;

export function GetSSID():Promise<string>;

export function OpenDirectoryDialog(arg1:any):Promise<string>;

export function PopulateImages():Promise<Array<string>>;
