// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImageThumbnail(arg1) {
  return window['go']['main']['App']['GetImageThumbnail'](arg1);
}

export function GetSSID() {
  return window['go']['main']['App']['GetSSID']();
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function PopulateImages() {
  return window['go']['main']['App']['PopulateImages']();
}
