// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetImageScreennail(arg1:string):Promise<types.ImageResponse>;

export function PopulateImages():Promise<Array<string>>;
