// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImageScreennail(arg1) {
  return window['go']['main']['App']['GetImageScreennail'](arg1);
}

export function PopulateImages() {
  return window['go']['main']['App']['PopulateImages']();
}
